### ISSUE TITLE
Logo shrinks in dark mode

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/website#2]
![Screenshot 2020-09-18 at 11 55 33 AM](https://user-images.githubusercontent.com/64214252/93618933-f2ffec80-f9a5-11ea-9925-80a6f1f1b91c.png)
Vs.
![Screenshot 2020-09-18 at 11 55 27 AM](https://user-images.githubusercontent.com/64214252/93618943-f6937380-f9a5-11ea-8690-c10de81b70d1.png)
It's pretty self explanatory

**Comment by Hans5958** [comment]
It is by design. On the dark mode, when it is bigger, there is only a little margin between the logo and the text because of the orange padding. In the light mode, because of the orange padding become one with the orange navigation bar, the logo (which is the S) will look smaller, so I made it larger.
