### ISSUE TITLE
Delete loading bar?

### ISSUE THREAD

**Issue by jemunm378** [ScratchAddons/website#20]
The loading bar goes slow on some computers. And, in some cases, it stops at 99%. You could probably fix the issue by deleting the loading bar?

**Comment by JeffaloBob** [comment]
yeah, it's super intrusive and i don't think it's necessary

**Comment by Hans5958** [comment]
The issue is not quite the loading bar, but the fact that it hides the whole website first to give time the dark theme to kick in. This was first implemented by @WorldLanguages because he didn't want users have the flash when initializing the dark theme. I only added the loading bar to fill the awkward emptiness while waiting it to load.

There should not any difference between having the so called "loading screen", with the loading bar or not. However, I understand the reaction that some user gets. Still, I'm not sure if it is possible to just removing the loading screen with a compromise the awkward white page works, or  to just change the loading bar, or to remove the "loading screen" completely with a compromise of the mentioned flash from the said initialization.

@WorldLanguages, what do you think?

**Comment by Hans5958** [comment]
FYI, turns out that it also checks for event loop lag signaling. I have turned it off in hopes that it load slow anymore.

**Comment by GrahamSH-LLK** [comment]
The loading thing is quite annoying. It just looks awkward.

**Comment by Hans5958** [comment]
Okay, it was still broken after the fix because of JSON errors. I have fixed it. Loading times should be shortened significantly

**Comment by JeffaloBob** [comment]
meh honestly I'd rather have it flash, the loading bar looks pretty unprofessional

**Comment by Hans5958** [comment]
How is it unprofessional? Keep in mind that having the blank page while loading also an option.

**Comment by jemunm378** [comment]
Most websites today don't use loading bars.

**Comment by JeffaloBob** [comment]
i rather blank screen, loading bar feels like im opening some flash game from 2001 or something

**Comment by Hans5958** [comment]
Okay, got a faster loading method, which means I can remove Pace.js and you will see the white screen in less time.
